refactor: хранение данных заменено на хранение в БД
Feirina/java-filmorate pull request #3
Opened 2022-09-11 15:50 UTC by Feirina

2022-09-11 20:45 UTC, Frilock requested changes
Добрый день, в целом все ок, пара мелких комментариев к работе. Обратите внимание на комментарий про NPE.

2022-09-11 20:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private Integer id;
Не знаю писал ли в прошлые разы, но лучше в качестве идентификатора использовать long, чтобы проблема переполнения была максимально нереальной

2022-09-11 20:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilm(id) == null) throw new NotFoundException("Фильма с данным id не существует");
Лучше все таки обособлять выражения, дабы не допускать ошибок по невнимательности

2022-09-11 20:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +public class MpaService {
Можно для классов сервисов, где есть методы getById и getAll сделать общий интерфейс

2022-09-11 20:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            statement.setString(1, film.getName());
Можно маппинг в отдельный метод вынести

2022-09-11 20:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Film makeFilm(ResultSet rs) throws SQLException {
Можно в отдельный класс mapper вынести

2022-09-11 20:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                .releaseDate(rs.getDate("release_date").toLocalDate())
Смотрите, поле даты всегда заполняется? Вы не получите тут NPE при обращении .toLocalDate? Вообще бы лучше проверить, что (rs.getDate("release_date") != null

2022-09-11 20:45 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/friends/FriendsDbStorage.java
> +    private User makeUser(ResultSet rs) throws SQLException {
Тоже можно в отдельный класс мапер вынести

2022-09-18 12:03 UTC, Frilock requested changes
Добрый день, еще в одном месте в маппере не проверили ситуацию с NPE. Или там поле всегда заполняется? Можете мне в комментарии ответить и прислать работу снова.

2022-09-18 12:03 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/Mappers.java
> +                .birthday(rs.getDate("birthday").toLocalDate())
А почему тут не проверили?

2022-09-18 13:25 UTC, Feirina commented on src/main/java/ru/yandex/practicum/filmorate/storage/Mappers.java
> +                .birthday(rs.getDate("birthday").toLocalDate())
В итоге решила добавить проверку на null в  валидацию user, чтобы без даты рождения нельзя было создать user, ведь по идеи в фильмах у нас есть возрастной рейтинг, значит пользователь должен указать свой возраст при регистрации

2022-09-18 13:36 UTC, Frilock approved these changes
Принято

2022-09-30 05:52 UTC, merged